execute_process(COMMAND "${SERVERD}" --help RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "serverd --help failed: ${rc}")
endif()
set(text "${out}${err}")
string(FIND "${text}" "bind address (default 127.0.0.1)" found)
if(found EQUAL -1)
    message(FATAL_ERROR "serverd help must document the loopback default")
endif()
string(FIND "${text}" "bind address (default 0.0.0.0)" stale)
if(NOT stale EQUAL -1)
    message(FATAL_ERROR "serverd help still advertises the stale public default")
endif()
